//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISampleService")]
    public interface ISampleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PingAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/PingComplexModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.ComplexModelResponse> PingComplexModelAsync(ServiceReference.ComplexModelInput inputModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/IntArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.IntArrayResponse> IntArrayAsync(ServiceReference.IntArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/ComplexReturnModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.ComplexReturnModelResponse> ComplexReturnModelAsync(ServiceReference.ComplexReturnModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/VoidMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="s")]
        System.Threading.Tasks.Task<string> VoidMethodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/AsyncMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> AsyncMethodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/NullableMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.NullableMethodResponse> NullableMethodAsync(ServiceReference.NullableMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/XmlMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task XmlMethodAsync(System.Xml.XmlElement xml);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplexModelInput
    {
        
        private string stringPropertyField;
        
        private int intPropertyField;
        
        private string[] listPropertyField;
        
        private DateTimeOffset dateTimeOffsetPropertyField;
        
        private ComplexObject[] complexListPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StringProperty
        {
            get
            {
                return this.stringPropertyField;
            }
            set
            {
                this.stringPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntProperty
        {
            get
            {
                return this.intPropertyField;
            }
            set
            {
                this.intPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public string[] ListProperty
        {
            get
            {
                return this.listPropertyField;
            }
            set
            {
                this.listPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DateTimeOffset DateTimeOffsetProperty
        {
            get
            {
                return this.dateTimeOffsetPropertyField;
            }
            set
            {
                this.dateTimeOffsetPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        public ComplexObject[] ComplexListProperty
        {
            get
            {
                return this.complexListPropertyField;
            }
            set
            {
                this.complexListPropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class DateTimeOffset
    {
        
        private System.DateTime dateTimeField;
        
        private short offsetMinutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short OffsetMinutes
        {
            get
            {
                return this.offsetMinutesField;
            }
            set
            {
                this.offsetMinutesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplexReturnModel
    {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplexModelResponse
    {
        
        private float floatPropertyField;
        
        private string stringPropertyField;
        
        private string[] listPropertyField;
        
        private DateTimeOffset dateTimeOffsetPropertyField;
        
        private TestEnum testEnumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float FloatProperty
        {
            get
            {
                return this.floatPropertyField;
            }
            set
            {
                this.floatPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StringProperty
        {
            get
            {
                return this.stringPropertyField;
            }
            set
            {
                this.stringPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public string[] ListProperty
        {
            get
            {
                return this.listPropertyField;
            }
            set
            {
                this.listPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DateTimeOffset DateTimeOffsetProperty
        {
            get
            {
                return this.dateTimeOffsetPropertyField;
            }
            set
            {
                this.dateTimeOffsetPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TestEnum TestEnum
        {
            get
            {
                return this.testEnumField;
            }
            set
            {
                this.testEnumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TestEnum
    {
        
        /// <remarks/>
        One,
        
        /// <remarks/>
        Two,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplexObject
    {
        
        private string stringPropertyField;
        
        private int intPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StringProperty
        {
            get
            {
                return this.stringPropertyField;
            }
            set
            {
                this.stringPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IntProperty
        {
            get
            {
                return this.intPropertyField;
            }
            set
            {
                this.intPropertyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IntArray", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IntArrayRequest
    {
        
        public IntArrayRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IntArrayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IntArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public int[] IntArrayResult;
        
        public IntArrayResponse()
        {
        }
        
        public IntArrayResponse(int[] IntArrayResult)
        {
            this.IntArrayResult = IntArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComplexReturnModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComplexReturnModelRequest
    {
        
        public ComplexReturnModelRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComplexReturnModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComplexReturnModelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ServiceReference.ComplexReturnModel[] ComplexReturnModelResult;
        
        public ComplexReturnModelResponse()
        {
        }
        
        public ComplexReturnModelResponse(ServiceReference.ComplexReturnModel[] ComplexReturnModelResult)
        {
            this.ComplexReturnModelResult = ComplexReturnModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NullableMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NullableMethodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> arg;
        
        public NullableMethodRequest()
        {
        }
        
        public NullableMethodRequest(System.Nullable<bool> arg)
        {
            this.arg = arg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NullableMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NullableMethodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NullableMethodResult;
        
        public NullableMethodResponse()
        {
        }
        
        public NullableMethodResponse(System.Nullable<int> NullableMethodResult)
        {
            this.NullableMethodResult = NullableMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ISampleServiceChannel : ServiceReference.ISampleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SampleServiceClient : System.ServiceModel.ClientBase<ServiceReference.ISampleService>, ServiceReference.ISampleService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SampleServiceClient() : 
                base(SampleServiceClient.GetDefaultBinding(), SampleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISampleService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SampleServiceClient.GetBindingForEndpoint(endpointConfiguration), SampleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SampleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SampleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string s)
        {
            return base.Channel.PingAsync(s);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ComplexModelResponse> PingComplexModelAsync(ServiceReference.ComplexModelInput inputModel)
        {
            return base.Channel.PingComplexModelAsync(inputModel);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.IntArrayResponse> ServiceReference.ISampleService.IntArrayAsync(ServiceReference.IntArrayRequest request)
        {
            return base.Channel.IntArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.IntArrayResponse> IntArrayAsync()
        {
            ServiceReference.IntArrayRequest inValue = new ServiceReference.IntArrayRequest();
            return ((ServiceReference.ISampleService)(this)).IntArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ComplexReturnModelResponse> ServiceReference.ISampleService.ComplexReturnModelAsync(ServiceReference.ComplexReturnModelRequest request)
        {
            return base.Channel.ComplexReturnModelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ComplexReturnModelResponse> ComplexReturnModelAsync()
        {
            ServiceReference.ComplexReturnModelRequest inValue = new ServiceReference.ComplexReturnModelRequest();
            return ((ServiceReference.ISampleService)(this)).ComplexReturnModelAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> VoidMethodAsync()
        {
            return base.Channel.VoidMethodAsync();
        }
        
        public System.Threading.Tasks.Task<int> AsyncMethodAsync()
        {
            return base.Channel.AsyncMethodAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.NullableMethodResponse> ServiceReference.ISampleService.NullableMethodAsync(ServiceReference.NullableMethodRequest request)
        {
            return base.Channel.NullableMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.NullableMethodResponse> NullableMethodAsync(System.Nullable<bool> arg)
        {
            ServiceReference.NullableMethodRequest inValue = new ServiceReference.NullableMethodRequest();
            inValue.arg = arg;
            return ((ServiceReference.ISampleService)(this)).NullableMethodAsync(inValue);
        }
        
        public System.Threading.Tasks.Task XmlMethodAsync(System.Xml.XmlElement xml)
        {
            return base.Channel.XmlMethodAsync(xml);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISampleService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISampleService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5116/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SampleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISampleService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SampleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISampleService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISampleService_soap,
        }
    }
}
